// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240318163442_new values")]
    partial class newvalues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.ComprobanteFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Itebis")
                        .HasColumnType("float");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.Property<string>("NCF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RncCedula")
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("RncCedula");

                    b.ToTable("ComprobantesFiscales");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e8a0bd8-bed9-4908-b94a-b956f3efbd0f"),
                            Itebis = 450.0,
                            Monto = 2500.0,
                            NCF = "E310000000001",
                            RncCedula = "04000175463"
                        },
                        new
                        {
                            Id = new Guid("b3934379-8b84-4e23-8fc6-7f6bcf9181e4"),
                            Itebis = 486.0,
                            Monto = 2700.0,
                            NCF = "E310000000002",
                            RncCedula = "045788655"
                        },
                        new
                        {
                            Id = new Guid("31b1ab73-a9fd-4937-a93b-362db6b1e60c"),
                            Itebis = 486.0,
                            Monto = 2700.0,
                            NCF = "E310000000003",
                            RncCedula = "98754321012"
                        },
                        new
                        {
                            Id = new Guid("d295ee8e-3fcd-4226-a7d4-1b92282b2d4e"),
                            Itebis = 414.0,
                            Monto = 2300.0,
                            NCF = "E310000000004",
                            RncCedula = "045788655"
                        });
                });

            modelBuilder.Entity("Entities.Contributor", b =>
                {
                    b.Property<Guid>("ContributorId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RncCedula")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ContributorId");

                    b.ToTable("Contributors", (string)null);

                    b.HasData(
                        new
                        {
                            ContributorId = new Guid("6ec9c3a5-869b-474a-bf16-ff21f1aead0a"),
                            Name = "CRISTINO ALMANZAR",
                            RncCedula = "04000175463",
                            Status = 1,
                            Type = "PERSONA FISICA"
                        },
                        new
                        {
                            ContributorId = new Guid("fd29c1ac-d8d1-4bd2-bd37-bb3684d0437b"),
                            Name = "MARIO MARTINEZ",
                            RncCedula = "045788655",
                            Status = 1,
                            Type = "PERSONA FISICA"
                        });
                });

            modelBuilder.Entity("Entities.ComprobanteFiscal", b =>
                {
                    b.HasOne("Entities.Contributor", "Contributor")
                        .WithMany("ComprobantesFiscales")
                        .HasForeignKey("RncCedula")
                        .HasPrincipalKey("RncCedula");

                    b.Navigation("Contributor");
                });

            modelBuilder.Entity("Entities.Contributor", b =>
                {
                    b.Navigation("ComprobantesFiscales");
                });
#pragma warning restore 612, 618
        }
    }
}
